services: 
  ql-db:
    build:
      context: ./postgres
      dockerfile: dockerfile.postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "ql"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ql_db:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
  pgadmin:
    build:
      context: ./pgadmin4
      dockerfile: dockerfile.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
volumes:
  ql_db:
  pgadmin_data:
  
